//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alytalomob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuoneLampotila
    {
        public int HuoneID { get; set; }
        public string HuoneenNimi { get; set; }
        public Nullable<int> Lampotila { get; set; }
    }
}
