//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alytalomob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuoneLampo
    {
        public int HuoneID { get; set; }
        public string Huone_Nimi { get; set; }
        public Nullable<int> LampoNyt { get; set; }
        public Nullable<int> LampoPaalla { get; set; }
        public Nullable<bool> LampoOn { get; set; }
        public Nullable<bool> LampoOff { get; set; }
        public string Tila { get; set; }
    }
}
