//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alytalomob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valot
    {
        public int ValoID { get; set; }
        public string Huone { get; set; }
        public Nullable<bool> ValotPois { get; set; }
        public Nullable<bool> Valot33 { get; set; }
        public Nullable<bool> Valot66 { get; set; }
        public Nullable<bool> Valot100 { get; set; }
        public string Tila { get; set; }
    }
}
